### ISSUE TITLE
Work with GHC 8.0?

### ISSUE THREAD

**Issue by seanhess** [hdevtools/hdevtools#23]
Hi, it looks like you've updated the code to support GHC 8.0, but haven't published it yet? Could you publish so it gets into Stackage nightly? Alternatively, do you know how I might install the latest hdevtools in the meantime?

Thank you!

**Comment by ch1bo** [comment]
I have release 1.3.2 and issued a [PR](https://github.com/fpco/stackage/pull/1593). I haven't tried the fix though and it seems that the stackage travis job fails with my branch.

In the meantime you can just check out hdevtools master, update the stack.yaml to use compiler=8.0.1, fix the dependency issues the travis job is seeing and submit a PR ;)

**Comment by ch1bo** [comment]
hdevtools should be re-enabled for stackage again, and will land in the next nightly I suppose. Please close this issue if that is the case.

**Comment by seanhess** [comment]
I installed `hdevtools-0.1.3.2` via stack with stackage nightly: https://www.stackage.org/nightly-2016-06-12. The install went well, no issues. I went back to my project (ghc 8, stack). I set the resolver to the same nightly snapshot and rebuilt. But I get an error when I try to check my code.

```
$ hdevtools --version
hdevtools: version 0.1.3.2 (ghc-8.0.1-x86_64-darwin, cabal-1.24.0.0)

$ hdevtools check src/Main.hs
Cabal error: ghc-pkg dump failed
```

**Comment by seanhess** [comment]
Wait, that's expected, right? I need to do something fancy to get it to load the local package database. I only tried that step because my editor (vim with syntanstic) wasn't showing the errors. Let me see if I can get that command in correctly.

**Comment by seanhess** [comment]
Still getting the error after using the command suggested in the README. 

```
$ stack exec --no-ghc-package-path hdevtools -- check src/Main.hs
Cabal error: ghc-pkg dump failed
```

**Comment by ch1bo** [comment]
Just downloaded ghc-8.0.1 and tried to reproduce your error on hdevtools's source as well as a small project at work. To no avail, works perfectly fine for me.

What happens if you call `ghc-pkg dump` or `stack --resolver=nightly-2016-06-12 exec ghc-pkg -- dump` directly?

**Comment by ch1bo** [comment]
Got it, because you tried direct invocation of `hdevtools` first, the server process was still alive - indicated by and only stopped when the unix domain socket `.hdevtools.sock` in the working directory is killed/removed. The call without using `stack exec` uses the `ghc` and `ghc-pkg` from your path, which is most likely not a ghc-8.01. 

Removing `.hdevtools.sock` from your working directory will resolve your problem.

I should really draft a ticket on how to kill a server with non-matching ghc, cabal or hdevtools version.

**Comment by seanhess** [comment]
Yes it's working now, thank you! Sorry for the false alarm. Thanks for your hard work on the tool!

**Comment by ryskajakub** [comment]
Hi, I had a similar error here. I was trying to use the hdevtools with stack, but old stale cabal sandbox files were floating around in my project dir. Hdevtools still tries to use it, even though stack is present. I think optimal would be to ignore cabal-install tools if stack is present since stack is newer hence people probably meant to use that if both are present.

**Comment by ryskajakub** [comment]
The suspicious lines are here:
https://github.com/hdevtools/hdevtools/blob/master/src/Cabal.hs#L142-L145
