### ISSUE TITLE
Linking error when using template haskell

### ISSUE THREAD

**Issue by Ongy** [hdevtools/hdevtools#37]
Using `hdevtools check` with a file that uses template haskell, direct in an imported module, fails in a linker step for ghci:

>ByteCodeLink.lookupCE
>During interactive linking, GHCi couldn't find the following symbol:
>  monkyzm2zi0zi1zi1zmIZZax6R8K8W72umuzz6hs2tf_MonkyziTemplate_importLib_closure
>This may be due to you not asking GHCi to load extra object files,
>archives or DLLs needed by your current session.  Restart GHCi, specifying
>the missing library using the -L/path/to/object/dir and -lmissinglibname
>flags, or simply by naming the relevant files on the GHCi command line.
>Alternatively, this link failure might indicate a bug in GHCi.
>If you suspect the latter, please send a bug report to:
>  glasgow-haskell-bugs@haskell.org

I encountered this while testing hdevtools with [monky](https://github.com/monky-hs/monky).
In the `Monky.Modules` hdevtools can be used without problems. Files including (direct or transitiv) `Monky.Template` produce the error.

A similar error (different symbol missing) is produced trying to check `bin/Main.hs` which includes `Monky.Version` which also uses template haskell.

**Comment by Ongy** [comment]
I created https://github.com/hdevtools/hdevtools/pull/38 for this.

**Comment by lwm** [comment]
Running `hdevtools` while hacking on `commercialhaskell/stack` got me:

> ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  stackzm1zi2zi1zm8BoyR8YmtMHCFDGIVo3HRA_SystemziProcessziLog_withProcessTimeLog_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org

Hoping to see your fix coming in soon @Ongy !

**Comment by ch1bo** [comment]
Merged with #38
